name: Docker Image CI Manual Job

on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          Upstream git branch or tag
        required: true
        default: 'master'
      build_dependencies:
        description: |
          List of apk packages to install prior to image building
        required: true
        default: 'npm yarn'
          

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"
  UPSTREAM: "ngoduykhanh/wireguard-ui"

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        
    - name: Checkout upstream repository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.UPSTREAM }}
        ref: ${{ github.event.inputs.tag }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      id: buildx
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:master
          network=host
          
    - name: Get info
      id: repo
      run: |
        echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY#*/})"
        echo "::set-output name=sha::$(git rev-parse --verify ${{ github.event.inputs.tag }})"
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}},priority=900,value=${{ github.event.inputs.tag }}
          type=edge,priority=700,branch=${{ github.event.inputs.tag }}
          type=match,pattern=master,group=0,value=${{ github.event.inputs.tag }}
          type=raw,value=${{ steps.repo.outputs.sha }}
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_DEPENDENCIES=${{ github.event.inputs.build_dependencies || 'npm yarn' }}
          
