name: Docker Image CI

on:
  repository_dispatch:
    types: 
      - trigger-ci

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Get current repository name
      id: repo
      run: >
        echo "::set-output name=name::$(echo ${GITHUB_REPOSITORY#*/})"
      
    - name: Check secrets availability
      id: checksecrets
      shell: bash
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        vars=(
          $DOCKERHUB_USERNAME
          $DOCKERHUB_TOKEN
        )

        while IFS= read -r var; do
          if [[ -z ${var} ]]; then
            echo ::set-output name=secretspresent::false
            break
          else
            echo ::set-output name=secretspresent::true
          fi
        done <<< "${vars[@]}"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      id: buildx
      with:
        install: true
        driver: docker-container
        driver-opts: |
          image=moby/buildkit:master
          network=host
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.4.1
      with:
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo.outputs.name }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=edge,priority=700,value=${{ github.event.client_payload.branch }}
          type=raw,priority=200,value=SHA${{ github.event.client_payload.sha }}
          type=semver,priority=900,pattern={{version}},value=${{ github.event.client_payload.ref }}
          type=match,pattern=master,group=0,value=${{ github.event.inputs.tag }}
    
    - name: Log in to the Container registry
      if: env.REGISTRY
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Log in to Docker Hub
      if: steps.checksecrets.outputs.secretspresent == 'true'
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.upstream }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
